name: Deploy Typst PDF to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          lfs: true
      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Ensure yq is available
        run: |
          if ! command -v yq &> /dev/null; then
            sudo wget -qO /usr/local/bin/yq \
              https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod +x /usr/local/bin/yq
          fi

      - name: Prepare metadata.yml
        env:
          STUDENT_FIRST_NAME: ${{ secrets.STUDENT_FIRST_NAME }}
          STUDENT_LAST_NAME:  ${{ secrets.STUDENT_LAST_NAME }}
          STUDENT_EMAIL:      ${{ secrets.STUDENT_EMAIL }}
          STUDENT_ID:         ${{ secrets.STUDENT_ID }}
          STUDENT_GREEN_TYPE: ${{ secrets.STUDENT_GREEN_TYPE }}
        run: |
          mv report/example.metadata.yml report/metadata.yml

          yq -i '
            .studentFirstName = strenv(STUDENT_FIRST_NAME) |
            .studentLastName  = strenv(STUDENT_LAST_NAME)  |
            .studentEmail     = strenv(STUDENT_EMAIL)      |
            .studentID        = strenv(STUDENT_ID)         |
            .greenType        = strenv(STUDENT_GREEN_TYPE)
          ' report/metadata.yml

      - name: Compile Typst to PDF
        if: success()
        run: |
          mkdir dist
          typst c report/main.typ dist/assignment.pdf --root .

      - name: Adds index.html
        if: success()
        run: cp index.html dist/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
